### ISSUE TITLE
Update CoC to ban brands

### ISSUE THREAD

**Issue by lynncyrin** [TootCat/mastodon#13]

**Comment by ubiquill** [comment]
we should probably add some guidance for self promotion as well. I think there is a big difference between an indie artist posting a link to  their etsy and a brand. We should probably distinguish that somehow.

**Comment by lynnco** [comment]
Yea, we want wording that allows artists making $200/month to talk about their patreon, while also disallowing Walmart

**Comment by wavebeem** [comment]
Definitely!

**Comment by EmilePouget** [comment]
Including late night mistakes and casual language, how about:

We encourage independent artists or people in jobs otherwise dependent on self-promotion to use our platform for occasional (note: needs better wording for something which avoids a constant flood of what could be considered spam) advertisment from their profiles. Needs better wording: Big business, like for example: ebay, facebook, walmart, etc with an income in he millions are adviced to not use this platform as an advertisment outlet.

**Comment by wavebeem** [comment]
That seems like a reasonable angle to me

**Comment by EmilePouget** [comment]
I think it needs to be more specific, so that arbitrary decisions can be ruled out and people know where the line is drawn. In case the line is too vague, it's not bad because asking wether this is okay should be encouraged (though it is not a welcome effect as long as it can be avoided).

**Comment by iangreenleaf** [comment]
A couple ideas on how you could frame this:

* You could state that real people who occasionally promote their own work is fine, but accounts dedicated to a company or brand are not.

* You could draw the line at accounts whose *primary* purpose is self-promotion. This wording would make it pretty clear what's available while still leaving you some leeway for "we'll know it when we see it" enforcement.

**Comment by EmilePouget** [comment]
A brand could try to be in contact with people who buy their products without advertisment, for example collectives, syndicates, genossenschaften and similar organized groups.
For example Premium produces Cola in Germany and is organized in a collective. I think the possibility for those who don't want to make money from advertisment and still announce occasionally (define: occasionally) news on what they work but they happen to be no individual but a group, how is this grey area defined?
At which point do news posts become an annoyance? I am opposed to any kind of marketing, the most cruel form I meet in my home, average 2 visits per week from people who think that I have interest in a new electricity, ISP, etc contract.

What if someone for whatever reason is really into Porsche and their whole life circles around Porsche products? Are they advertising or just sharing their point of view with the world?
For me, advertising accounts start where you are led through tracking links (other people call them url shorteners) to their shop, and every post is basically a form of aggressive marketing in 140 - 500 characters. Often it can even be dialogue based:
A: My phone is so terrible, I wished Samsung would produce something better!
B: Oh, have you heard of our new amazing competionless superphone, only available for 0.99 ISK? You will love it, it's the best! Have I told you it's the best? Here's a link to our shop btw: foo.trackme.123.no.br

So, the definition is difficult. I can go on about this for a long time. Do we take dictionary definitions? Common sense definitions? A combination of both?
Primary purpose for promotion of products as described above in an aggressive, invasive way would be where I would draw the line.

**Comment by lynnco** [comment]
Whatever we end up with, I want to explicitly allow posts like https://toot.cat/@audrey/388059

**Comment by EmilePouget** [comment]
I fully agree :)

**Comment by mkzero** [comment]
Even if they advertise - there's one simple thing you can do if that's not your thing: Unfollow/Block them. Maybe people want to get to that shop? Or just introduce a flag to Upstream that allows to say "I do advertisement by the definition of [insert definition]" and allow users just to block that instead of going around and blocking instances because they allow brands or companies to simply exist.
